version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: weekly
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
        interval: "weekly"
