using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ModelContextProtocol.SourceGenerators;

/// <summary>
/// Source generator that creates Description attributes from XML comments
/// for partial methods tagged with McpServerTool attribute.
/// </summary>
[Generator]
public class XmlToDescriptionGenerator : ISourceGenerator
{
    private const string McpServerToolAttributeName = "McpServerToolAttribute";
    private const string McpServerToolShortName = "McpServerTool";
    private const string DescriptionAttributeName = "System.ComponentModel.DescriptionAttribute";

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new McpToolSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not McpToolSyntaxReceiver receiver)
        {
            return;
        }

        foreach (var methodDeclaration in receiver.CandidateMethods)
        {
            var semanticModel = context.Compilation.GetSemanticModel(methodDeclaration.SyntaxTree);
            var methodSymbol = semanticModel.GetDeclaredSymbol(methodDeclaration);

            if (methodSymbol == null)
            {
                continue;
            }

            // Check if method has McpServerTool attribute
            if (!HasMcpServerToolAttribute(methodSymbol))
            {
                continue;
            }

            // Check if method already has a Description attribute
            if (HasDescriptionAttribute(methodSymbol))
            {
                continue;
            }

            // Check if this is a partial method
            if (!methodDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            {
                continue;
            }

            // Extract XML documentation
            var xmlComment = GetXmlDocumentation(methodSymbol);
            if (string.IsNullOrWhiteSpace(xmlComment))
            {
                continue;
            }

            // Generate the partial method declaration with Description attribute
            var source = GeneratePartialMethodDeclaration(methodSymbol, methodDeclaration, xmlComment!);
            if (source != null)
            {
                var fileName = $"{methodSymbol.ContainingType.Name}_{methodSymbol.Name}_Description.g.cs";
                context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
            }
        }
    }

    private bool HasMcpServerToolAttribute(IMethodSymbol methodSymbol)
    {
        return methodSymbol.GetAttributes().Any(attr =>
        {
            var attrName = attr.AttributeClass?.Name;
            return attrName == McpServerToolAttributeName || attrName == McpServerToolShortName;
        });
    }

    private bool HasDescriptionAttribute(IMethodSymbol methodSymbol)
    {
        return methodSymbol.GetAttributes().Any(attr =>
            attr.AttributeClass?.ToDisplayString() == DescriptionAttributeName);
    }

    private string? GetXmlDocumentation(IMethodSymbol methodSymbol)
    {
        var xmlDoc = methodSymbol.GetDocumentationCommentXml();
        if (string.IsNullOrWhiteSpace(xmlDoc))
        {
            return null;
        }

        // Extract <summary> content
        var summaryStart = xmlDoc!.IndexOf("<summary>");
        var summaryEnd = xmlDoc.IndexOf("</summary>");

        if (summaryStart < 0 || summaryEnd < 0)
        {
            return null;
        }

        var summary = xmlDoc.Substring(summaryStart + 9, summaryEnd - summaryStart - 9);
        return CleanXmlDocText(summary);
    }

    private string CleanXmlDocText(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return string.Empty;
        }

        // Remove leading/trailing whitespace and normalize line breaks
        var lines = text.Split('\n')
            .Select(line => line.Trim())
            .Where(line => !string.IsNullOrEmpty(line));

        return string.Join(" ", lines).Trim();
    }

    private string? GeneratePartialMethodDeclaration(IMethodSymbol methodSymbol, MethodDeclarationSyntax methodDeclaration, string description)
    {
        var containingType = methodSymbol.ContainingType;
        if (containingType == null)
        {
            return null;
        }

        var namespaceName = containingType.ContainingNamespace?.ToDisplayString();
        if (string.IsNullOrEmpty(namespaceName) || namespaceName == "<global namespace>")
        {
            return null;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using ModelContextProtocol.Server;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        // Generate the containing type
        AppendTypeDeclaration(sb, containingType, () =>
        {
            // Add the Description attribute and partial method declaration
            sb.AppendLine($"    [Description(\"{EscapeString(description)}\")]");
            
            // Copy all modifiers
            var modifiers = string.Join(" ", methodDeclaration.Modifiers.Select(m => m.Text));
            sb.Append($"    {modifiers} ");

            // Add return type
            sb.Append($"{methodSymbol.ReturnType.ToDisplayString()} ");

            // Add method name
            sb.Append($"{methodSymbol.Name}");

            // Add parameters with their attributes
            sb.Append("(");
            var parameters = methodSymbol.Parameters.Select(p =>
            {
                var paramStr = $"{p.Type.ToDisplayString()} {p.Name}";
                return paramStr;
            });
            sb.Append(string.Join(", ", parameters));
            sb.AppendLine(");");
        });

        return sb.ToString();
    }

    private void AppendTypeDeclaration(StringBuilder sb, INamedTypeSymbol typeSymbol, System.Action appendBody)
    {
        var typeKeyword = typeSymbol.TypeKind switch
        {
            TypeKind.Class => "class",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => "class"
        };

        var modifiers = new List<string>();
        if (typeSymbol.DeclaredAccessibility == Accessibility.Public)
        {
            modifiers.Add("public");
        }
        else if (typeSymbol.DeclaredAccessibility == Accessibility.Internal)
        {
            modifiers.Add("internal");
        }

        if (typeSymbol.IsStatic)
        {
            modifiers.Add("static");
        }

        modifiers.Add("partial");

        sb.AppendLine($"{string.Join(" ", modifiers)} {typeKeyword} {typeSymbol.Name}");
        sb.AppendLine("{");
        appendBody();
        sb.AppendLine("}");
    }

    private string EscapeString(string text)
    {
        return text.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private class McpToolSyntaxReceiver : ISyntaxContextReceiver
    {
        public List<MethodDeclarationSyntax> CandidateMethods { get; } = new List<MethodDeclarationSyntax>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            // Look for method declarations with attributes
            if (context.Node is MethodDeclarationSyntax methodDeclaration &&
                methodDeclaration.AttributeLists.Count > 0)
            {
                CandidateMethods.Add(methodDeclaration);
            }
        }
    }
}
