using System.Text.Json.Serialization;

namespace ModelContextProtocol.Protocol.Types;

/// <summary>
/// Represents the type of role in the Model Context Protocol conversation.
/// The Role enum is a fundamental part of the MCP message exchange model, defining
/// who is speaking in a conversation between a user and an AI assistant.
/// </summary>
/// <remarks>
/// <para>
/// In the MCP communication flow, each message must be associated with a specific role to maintain
/// the conversation structure. The Role enum provides the two essential conversation participants:
/// User (human) and Assistant (AI).
/// </para>
/// <para>
/// When serialized to JSON, Role values are automatically converted to lowercase strings
/// using the <see cref="CustomizableJsonStringEnumConverter{TEnum}"/>. For example,
/// Role.User becomes "user" and Role.Assistant becomes "assistant" in JSON.
/// </para>
/// <para>
/// Roles are typically used when creating messages in a conversation context, such as in
/// <see cref="PromptMessage"/>, <see cref="SamplingMessage"/>, and when working with annotations
/// that target specific audience members.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Create a message from the user
/// var userMessage = new PromptMessage
/// {
///     Role = Role.User,
///     Content = new Content { Text = "What is quantum computing?", Type = "text" }
/// };
/// 
/// // Create a response from the assistant
/// var assistantMessage = new PromptMessage
/// {
///     Role = Role.Assistant,
///     Content = new Content { Text = "Quantum computing is a type of computation that...", Type = "text" }
/// };
/// 
/// // Use roles in annotations to target specific audiences
/// var content = new Content
/// {
///     Type = "text",
///     Text = "Debug: Processing user request",
///     Annotations = new() { Audience = [Role.Assistant], Priority = 0.3f }
/// };
/// </code>
/// </example>
/// <seealso cref="PromptMessage"/>
/// <seealso cref="SamplingMessage"/>
/// <seealso cref="Annotations"/>
/// <see href="https://github.com/modelcontextprotocol/specification/blob/main/schema/">See the schema for details</see>
[JsonConverter(typeof(CustomizableJsonStringEnumConverter<Role>))]
public enum Role
{
    /// <summary>
    /// Corresponds to the human user in the conversation.
    /// </summary>
    /// <remarks>
    /// The User role represents content, messages, or actions originating from a human user.
    /// In MCP conversations, User messages typically contain questions, commands, or information
    /// provided by the human participant. When serialized to JSON, this value appears as "user".
    /// </remarks>
    [JsonStringEnumMemberName("user")]
    User,

    /// <summary>
    /// Corresponds to the AI assistant in the conversation.
    /// </summary>
    /// <remarks>
    /// The Assistant role represents content, messages, or actions generated by the AI model.
    /// In MCP conversations, Assistant messages typically contain responses, answers, or information
    /// provided by the AI participant. When serialized to JSON, this value appears as "assistant".
    /// </remarks>
    [JsonStringEnumMemberName("assistant")]
    Assistant
}